package com.bioxx.tfc2.World.Layers;


public class GenLayerFuzzyZoomTFC extends GenLayerTFC
{
	public GenLayerFuzzyZoomTFC(long par1, GenLayerTFC par3GenLayer)
	{
		super(par1);
		super.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int xPos, int zPos, int xMax, int zMax)
	{
		int parentXPos = xPos >> 1;
		int parentZPos = zPos >> 1;
		int parentXMax = (xMax >> 1) + 3;
		int parentZMax = (zMax >> 1) + 3;
		int[] parentArray = this.parent.getInts(parentXPos, parentZPos, parentXMax, parentZMax);
		int[] workingArray = new int[parentXMax * 2 * parentZMax * 2];
		int var11 = parentXMax << 1;
		int var13;

		for (int z = 0; z < parentZMax - 1; ++z)
		{
			var13 = z << 1;
			int thisCell = var13 * var11;
			int downLeft = parentArray[0 + (z + 0) * parentXMax];
			int upLeft = parentArray[0 + (z + 1) * parentXMax];

			for (int x = 0; x < parentXMax - 1; ++x)
			{
				this.initChunkSeed((long)(x + parentXPos << 1), (long)(z + parentZPos << 1));
				int downRight = parentArray[x + 1 + (z + 0) * parentXMax];
				int upRight = parentArray[x + 1 + (z + 1) * parentXMax];
				workingArray[thisCell] = downLeft;
				workingArray[thisCell++ + var11] = this.choose(downLeft, upLeft);
				workingArray[thisCell] = this.choose(downLeft, downRight);
				workingArray[thisCell++ + var11] = this.choose(downLeft, downRight, upLeft, upRight);
				downLeft = downRight;
				upLeft = upRight;
			}
		}

		int[] outArray = new int[xMax * zMax];

		for (var13 = 0; var13 < zMax; ++var13)
			System.arraycopy(workingArray, (var13 + (zPos & 1)) * (parentXMax << 1) + (xPos & 1), outArray, var13 * xMax, xMax);

		return outArray;
	}

	/**
	 * randomly choose between the two args
	 */
	protected int choose(int par1, int par2)
	{
		return this.nextInt(2) == 0 ? par1 : par2;
	}

	/**
	 * randomly choose between the four args
	 */
	protected int choose(int par1, int par2, int par3, int par4)
	{
		int var5 = this.nextInt(4);
		return var5 == 0 ? par1 : (var5 == 1 ? par2 : (var5 == 2 ? par3 : par4));
	}
}
