package com.bioxx.tfc2.World.Layers;



public class GenLayerZoomTFC extends GenLayerTFC
{
	public GenLayerZoomTFC(long seed, GenLayerTFC par3GenLayer)
	{
		super(seed);
		super.parent = par3GenLayer;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int areaX, int areaY, int areaWidth, int areaHeight)
	{
		int i1 = areaX >> 1;
		int j1 = areaY >> 1;
		int k1 = (areaWidth >> 1) + 2;
		int l1 = (areaHeight >> 1) + 2;
		int[] aint = this.parent.getInts(i1, j1, k1, l1);
		int i2 = k1 - 1 << 1;
		int j2 = l1 - 1 << 1;
		int[] aint1 = new int[i2 * j2];
		int l2;

		for (int k2 = 0; k2 < l1 - 1; ++k2)
		{
			l2 = (k2 << 1) * i2;
			int i3 = 0;
			int j3 = aint[i3 + 0 + (k2 + 0) * k1];

			for (int k3 = aint[i3 + 0 + (k2 + 1) * k1]; i3 < k1 - 1; ++i3)
			{
				this.initChunkSeed((long)(i3 + i1 << 1), (long)(k2 + j1 << 1));
				int l3 = aint[i3 + 1 + (k2 + 0) * k1];
				int i4 = aint[i3 + 1 + (k2 + 1) * k1];
				aint1[l2] = j3;
				aint1[l2++ + i2] = this.selectRandom(new int[] {j3, k3});
				aint1[l2] = this.selectRandom(new int[] {j3, l3});
				aint1[l2++ + i2] = this.selectModeOrRandom(j3, l3, k3, i4);
				j3 = l3;
				k3 = i4;
			}
		}

		int[] aint2 = new int[areaWidth * areaHeight];

		for (l2 = 0; l2 < areaHeight; ++l2)
		{
			System.arraycopy(aint1, (l2 + (areaY & 1)) * i2 + (areaX & 1), aint2, l2 * areaWidth, areaWidth);
		}

		return aint2;
	}

	/**
	 * Chooses one of the two inputs randomly.
	 */
	protected int choose(int par1, int par2)
	{
		return this.nextInt(2) == 0 ? par1 : par2;
	}

	protected int choose4(int id0, int id1, int id2, int id3)
	{
		if (id1 == id2 && id2 == id3)
			return id1;
		else if (id0 == id1 && id0 == id2)
			return id0;
		else if (id0 == id1 && id0 == id3)
			return id0;
		else if (id0 == id2 && id0 == id3)
			return id0;
		else if (id0 == id1 && id2 != id3)
			return id0;
		else if (id0 == id2 && id1 != id3)
			return id0;
		else if (id0 == id3 && id1 != id2)
			return id0;
		else if (id1 == id0 && id2 != id3)
			return id1;
		else if (id1 == id2 && id0 != id3)
			return id1;
		else if (id1 == id3 && id0 != id2)
			return id1;
		else if (id2 == id0 && id1 != id3)
			return id2;
		else if (id2 == id1 && id0 != id3)
			return id2;
		else if (id2 == id3 && id0 != id1)
			return id2;
		else if (id3 == id0 && id1 != id2)
			return id2;
		else if (id3 == id1 && id0 != id2)
			return id2;
		else if (id3 == id2 && id0 != id1)
			return id2;
		else
		{
			int rand = this.nextInt(4);
			return rand == 0 ? id0 : (rand == 1 ? id1 : (rand == 2 ? id2 : id3));
		}
	}

	public static GenLayerTFC magnify(long par0, GenLayerTFC par2GenLayer, int par3)
	{
		Object var4 = par2GenLayer;
		for (long var5 = 0; var5 < par3; ++var5)
			var4 = new GenLayerZoomTFC(par0 + var5, (GenLayerTFC) var4);
		return (GenLayerTFC) var4;
	}
}
