package com.bioxx.tfc2.World.Layers;

import net.minecraft.world.gen.layer.IntCache;

public class GenLayerIslandTFC extends GenLayerTFC
{
	public GenLayerIslandTFC(long par1)
	{
		super(par1);
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer subclass.
	 */
	@Override
	public int[] getInts(int pX, int pZ, int pWidth, int pHeight)
	{
		int[] outArray = IntCache.getIntCache(pWidth * pHeight);

		for (int z = 0; z < pHeight; ++z)
		{
			for (int x = 0; x < pWidth; ++x)
			{
				this.initChunkSeed(pX + x, pZ + z);
				if(((pX+x>>1) % 2 != 0) && ((pZ+z>>1) % 2 != 0) /*&& (this.nextInt(6) != 0)*/)
				{
					outArray[x + z * pWidth] = 1;	
				}
				else
				{
					outArray[x + z * pWidth] = 0;
				}
			}
		}

		if (pX > -pWidth && pX <= 0 && pZ > -pHeight && pZ <= 0)
			outArray[-pX + -pZ * pWidth] = 1;

		return outArray;
	}
}
